Feature/dev
freddykaberuka/food-recipes pull request #30
Opened 2022-06-04 22:56 UTC by freddykaberuka

## Completed Task

- Choose images, text, icons, fonts.
- Create the main part of the homepage that keeps the layout from the wireframe:
- Create footer according to the wireframe:
- Set up Gitflow
- Set up webpack
- Set up a JavaScript testing library (Jest)
- Implement the "add new comment" form on the Comments pop up according to the wireframe:
- display comment
- display number of likes
- add likes
- add popup of comment
- add testing of comments and likes
- add header

## Demo Link

https://drive.google.com/file/d/1y-KlGYcJbyYf4d9zB6REEXnQEp0uwc_A/view?usp=sharing

2022-06-04 23:27 UTC, AnselemOdims requested changes
### Hi , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Good job on the video presentation but please highlight a piece of code that you are proud of.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-04 23:27 UTC, AnselemOdims commented on src/modules/comment.js
> +        comment: textArea,
- [ ] Please kindly ensure that a user is able to add comments as I am unable to do that at the moment.
- [ ] At the moment, when you click any part of the modal it disappears, please kindly make sure the modal only disappears when the `X` button is clicked.

2022-06-04 23:27 UTC, AnselemOdims commented on src/index.html
> +    </main>
- [ ] Please kindly make sure there is a counter in the homepage that displays the count of the items displayed

2022-06-04 23:27 UTC, AnselemOdims commented on src/index.js
> +
- [ ] Please kindly stick to using ES6 arrow function as per requirements.

2022-06-04 23:27 UTC, AnselemOdims commented on src/modules/comment.js
> +      .then((data) => {
- [ ] Please ensure that you use `async and await` for your API fetch calls

2022-06-04 23:27 UTC, AnselemOdims commented on src/modules/comment.js
> +    ).then(() => this.FetchComments(commentId));
- [ ] As pointed out earlier, please stick to using `async and await` for your fetch calls

2022-06-06 17:59 UTC, bellom commented
@freddykaberuka @Kayonga99 - It would be nice if you could stick to the [work and submission](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md#:~:text=Project%20requirements,Code%20Review%20carefully!) for this project. If you read the code review carefully, you notice you need to review each other's PRs (raise a PR from feature to dev), then ask for a code review request by creating a PR (raise a PR from dev to main branch)

If you have any questions, feel free to ask by dropping a comment on this PR.
CR Leader.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/31897434/172218039-c7d63ede-f8d0-4e84-861b-2552bfa42762.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/31897434/172218327-f65a5d5b-1cf6-4a4b-a153-7ec8083ba9b3.png">

2022-06-08 08:28 UTC, Davidosky007 commented on README.md
> +
* HEy @freddykaberuka  well done implementing all the requested changes your project would be approved soon 😄 , Please i would strongly suggest you improve your readme content so that it has set up instructions on how a visitor of your repo can successfully run your project locally and also update your live demo link as the one currenlty there leads to the leader board project 🙏

2022-06-09 17:58 UTC, merged